version: "3.10"

services:
  mongo:
    container_name: mongo
    image: mongo:5.0.14
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d

  bot:
    container_name: bot
    build: .
    volumes:
      - .:/code
      - products_volume:/code/products
    env_file:
      - .env
    restart: always
    depends_on:
      - mongo

  redis:
    container_name: redis
    image: redis:6.2.5
    restart: unless-stopped
    ports:
      - "6379:6379"

  celery-beat:
    container_name: celery-beat
    build: .
    command: celery -A tasks beat -l info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  celery-worker:
    container_name: celery-worker
    build: .
    command: celery -A tasks worker -l info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

volumes:
  products_volume: