version: "3.10"

services:
  bot:
    container_name: bot
    build: .
    volumes:
      - .:/code
      - products_volume:/code/products
    env_file:
      - .env
    restart: unless-stopped


  redis:
    container_name: redis
    image: redis:6.2.5
    ports:
      - "6379:6379"
    restart: unless-stopped

  celery-beat:
    container_name: celery-beat
    build: .
    command: celery -A tasks beat -l info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  celery-worker:
    container_name: celery-worker
    build: .
    command: celery -A tasks worker -l info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

volumes:
  products_volume: