version: "3.9"

services:
  bot:
    container_name: bot
    build: .
    volumes:
      - .:/code
      - products_volume:/code/products
    env_file:
      - .env
    restart: always

volumes:
  products_volume: